import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex flex-col min-h-screen bg-gray-200">
          <nav className="flex flex-row justify-start py-3 px-6 items-center gap-3 bg-white">
            <Image
            src="/img/logo.svg"
            width={35}
            height={35}
            alt="Logo"
            />
          <h1 className="font-bold text-xl"> Lista de paises</h1>

          </nav>
           <article className="p-6">
           {children}
           </article>
          </main>
      </body>
    </html>
  );
}
